### PR TITLE
standard C++ includes required for newer compilers. Added a .gitignore

### PR DESCRIPTION
**Pull request by mrpatrickwest**
clean compile of code
Fixed problem in the cedar catalog store
added a .gitignore

### CODE REVIEW

**Comment by jgallagher59701** [comment]
Patrick,

Will do once the fires subside…

Although I think you are an owner of that and can merge it yourself. If not, that seems odd and let me know and I’ll fix it.

James

PS. Are you here at EarthCube in DC?

> On May 22, 2015, at 6:23 PM, Patrick West notifications@github.com wrote:
> 
> clean compile of code
> Fixed problem in the cedar catalog store
> added a .gitignore
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/OPENDAP/cedar_handler/pull/1 https://github.com/OPENDAP/cedar_handler/pull/1
> Commit Summary
> 
> standard C++ includes required for newer compilers. Added a .gitignore
> File Changes
> 
> A .gitignore https://github.com/OPENDAP/cedar_handler/pull/1/files#diff-0 (38)
> Patch Links:
> 
> https://github.com/OPENDAP/cedar_handler/pull/1.patch https://github.com/OPENDAP/cedar_handler/pull/1.patch
> https://github.com/OPENDAP/cedar_handler/pull/1.diff https://github.com/OPENDAP/cedar_handler/pull/1.diff
> —
> Reply to this email directly or view it on GitHub https://github.com/OPENDAP/cedar_handler/pull/1.

## 

James Gallagher
jgallagher at opendap.org
406.723.8663

**Comment by jgallagher59701** [comment]
> On Jun 5, 2015, at 6:31 PM, Patrick West notifications@github.com wrote:
> 
> Merged #1 https://github.com/OPENDAP/cedar_handler/pull/1.
> 
> So I don’t need to look at this?

James

> —
> Reply to this email directly or view it on GitHub https://github.com/OPENDAP/cedar_handler/pull/1#event-324113250.

## 

James Gallagher
jgallagher at opendap.org
406.723.8663

**Comment by mrpatrickwest** [comment]
Nope, just some simple changes to get it to build, C++ headers, etc… And I fixed a problem so that cedar files and netcdf files could be used in the same server.

**Comment by jhrg** [comment]
> On Jun 7, 2015, at 12:32 AM, Patrick West notifications@github.com wrote:
> 
> Nope, just some simple changes to get it to build, C++ headers, etc… And I fixed a problem so that cedar files and netcdf files could be used in the same server.
> 
> Cool, Thanks!
> —
> Reply to this email directly or view it on GitHub https://github.com/OPENDAP/cedar_handler/pull/1#issuecomment-109614403.

## 

James Gallagher
jhrg at mac.com

**Pull request merged**
